"""List the records added and removed between the 8/11 baseline and each later gazette.

Covers 1150820 and 1150827 only.

A record is identified by (核定日期, 正個 land string) because 編號 is not stable.
Only the pre-cutoff set is compared, so newly approved rows are excluded.

    python scripts/gazette_churn.py --out docs/gazette-churn.md
"""
from __future__ import annotations

import argparse
import collections
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from build_project_aliases import iso_date, parcels_of, section_of  # noqa: E402
from urtpe.extract import extract_pdf  # noqa: E402

CUTOFF = "2026-08-11"
GAZETTES = [
    ("2026-08-11", ROOT / "source.pdf", None),
    ("2026-08-20", ROOT.parent / "urtpe-gazettes" / "核定案件-2026-08-20.pdf", "核定案件-2026-08-20.pdf"),
    ("2026-08-27", ROOT.parent / "urtpe-gazettes" / "核定案件-2026-08-27.pdf", "核定案件-2026-08-27.pdf"),
    # 1151002 is deliberately excluded: it is the newest gazette but carries 15
    # records whose 地號 cell the publisher truncated, so it is not a trustworthy
    # basis for churn measurement. See tasks.md 14.5.
]


def stage(name: str) -> str:
    if "概要案" in name:
        return "概要案"
    if "事業計畫" in name:
        return "事業計畫"
    return "other"


def key(r):
    return (iso_date(r), r["land"].replace(" ", ""))


def label(r) -> str:
    sec = section_of(r["land"]).replace("區", "", 1)
    ps = sorted(parcels_of(r["land"]))
    head = "、".join(ps[:3]) + ("…" if len(ps) > 3 else "")
    return "%s %s %s等%d筆" % (r["district"], sec, head, len(ps))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT / "docs" / "gazette-churn.md"))
    args = ap.parse_args()

    data = {}
    for gid, path, _ in GAZETTES:
        if not path.exists():
            print("MISSING %s" % path, file=sys.stderr)
            return 1
        rs = [r for r in extract_pdf(str(path)) if (iso_date(r) or "9999") <= CUTOFF]
        data[gid] = rs
        print("%s: %d pre-cutoff records" % (gid, len(rs)), file=sys.stderr)

    base = collections.Counter(key(r) for r in data["2026-08-11"])
    bykey = {gid: {key(r): r for r in rs} for gid, rs in data.items()}

    out = [
        "# Gazette churn against the 2026-08-11 baseline",
        "",
        "Generated by `scripts/gazette_churn.py`. Do not edit by hand.",
        "",
        "Records are matched on `(核定日期, land)`, because 編號 is not stable across",
        "publications. The comparison is restricted to approvals dated on or before",
        "**%s**, so rows newly approved after that date are excluded." % CUTOFF,
        "",
    ]

    summary = []
    for gid, _, fname in GAZETTES[1:]:
        cur = bykey[gid]
        lost_keys = [k for k in base if k not in cur]
        gained_keys = [k for k in cur if k not in base]
        summary.append((gid, fname, lost_keys, gained_keys, bykey, cur))

    out += ["| gazette | lost | gained | net |", "|---|---|---|---|"]
    for gid, _, lost_keys, gained_keys, _, _ in summary:
        out.append("| %s | %d | %d | %+d |" % (gid, len(lost_keys), len(gained_keys),
                                               len(gained_keys) - len(lost_keys)))
    out.append("")

    for gid, fname, lost_keys, gained_keys, bykey, cur in summary:
        out += ["---", "", "## %s vs 2026-08-11" % gid, ""]
        out += ["Source: `%s`" % fname, ""]

        for title, keys, lookup in (("Lost", lost_keys, bykey["2026-08-11"]),
                                    ("Gained", gained_keys, cur)):
            out += ["### %s (%d)" % (title, len(keys)), ""]
            if not keys:
                out += ["_none_", ""]
                continue
            by_year = collections.Counter(k[0][:4] for k in keys)
            out += ["By approval year: " + ", ".join(
                "%s×%d" % (y, n) for y, n in sorted(by_year.items())), ""]
            by_stage = collections.Counter(stage(lookup[k]["name"]) for k in keys if k in lookup)
            out += ["By stage: " + ", ".join(
                "%s×%d" % (s, n) for s, n in sorted(by_stage.items())), ""]
            out += ["| 核定日期 | 區 | 段/小段 | 筆 | 案名 | 階段 |",
                    "|---|---|---|---|---|---|"]
            for k in sorted(keys, key=lambda x: (x[0], x[1])):
                r = lookup.get(k)
                if r is None:
                    continue
                name = r["name"].replace("|", "\\|")
                sec = section_of(r["land"]).replace("區", "", 1)
                ps = parcels_of(r["land"])
                out.append("| %s | %s | %s | %d | %s | %s |"
                           % (k[0], r["district"], sec, len(ps), name, stage(r["name"])))
            out.append("")

    pathlib.Path(args.out).write_text("\n".join(out) + "\n", encoding="utf-8")
    print("written to %s" % args.out, file=sys.stderr)

    for gid, _, lost_keys, gained_keys, bykey, cur in summary:
        print("\n=== %s : lost %d, gained %d ===" % (gid, len(lost_keys), len(gained_keys)))
        for title, keys, lookup in (("lost", lost_keys, bykey["2026-08-11"]),
                                    ("gained", gained_keys, cur)):
            for k in sorted(keys, key=lambda x: (x[0], x[1])):
                r = lookup.get(k)
                if r is not None:
                    print("  %-4s %s  %s  %s" % (title[:4], k[0], label(r), stage(r["name"])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())