"""Generate a markdown reference for the stranded cache directories.

For each unmatched project, show what each of the four gazettes actually
contains for that unit, oldest publication first. This localises *when* a unit
left the list, which is the one question the PDFs cannot answer on their own.

    python scripts/stranded_report.py --out docs/stranded-cache-dirs.md
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from build_project_aliases import iso_date, jaccard, parcels_of, section_of  # noqa: E402
from urtpe.extract import extract_pdf  # noqa: E402

GAZETTES = [
    ("2026-08-11", ROOT / "source.pdf"),
    ("2026-08-20", ROOT.parent / "urtpe-gazettes" / "核定案件-2026-08-20.pdf"),
    ("2026-08-27", ROOT.parent / "urtpe-gazettes" / "核定案件-2026-08-27.pdf"),
    ("2026-09-24", ROOT.parent / "urtpe-gazettes" / "核定案件-2026-09-24.pdf"),
    ("2026-10-01", ROOT.parent / "urtpe-gazettes" / "核定案件-2026-10-01.pdf"),
]


def index_pdf(path: Path):
    out = []
    for r in extract_pdf(str(path)):
        out.append({
            "recno": r["recno"], "date": r["date"], "iso": iso_date(r),
            "district": r["district"], "name": r["name"], "land": r["land"],
            "sec": section_of(r["land"]), "parcels": parcels_of(r["land"]),
        })
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT / "docs" / "stranded-cache-dirs.md"))
    ap.add_argument("--threshold", type=float, default=0.2)
    args = ap.parse_args()

    aliases = json.loads((ROOT / "data" / "project_aliases.json").read_text(encoding="utf-8"))
    prev = json.loads((ROOT / "data" / "projects.previous.json").read_text(encoding="utf-8"))["projects"]
    by_pid = {p["project_id"]: p for p in prev}

    print("indexing gazettes...", file=sys.stderr)
    indexes = {}
    for gid, path in GAZETTES:
        if not path.exists():
            print(f"  MISSING {path}", file=sys.stderr)
            continue
        indexes[gid] = index_pdf(path)
        print(f"  {gid}: {len(indexes[gid])} records", file=sys.stderr)

    items = []
    for pid in aliases["unmatched"]:
        nodes = [n for n in by_pid[pid].get("nodes", []) if not n.get("orphan")]
        parcels, sections, iso = set(), set(), ""
        for n in nodes:
            parcels |= parcels_of(n.get("land", ""))
            sections.add(section_of(n.get("land", "")))
            iso = iso or iso_date(n)
        rows = []
        for gid, _ in GAZETTES:
            if gid not in indexes:
                rows.append((gid, None, 0, 0))
                continue
            best_j, best_rec = 0.0, None
            for r in indexes[gid]:
                if r["sec"] not in sections:
                    continue
                j = jaccard(parcels, r["parcels"])
                if best_rec is None or j > best_j:
                    best_j, best_rec = j, r
            if best_rec is None:
                rows.append((gid, None, 0, 0))
            else:
                rows.append((gid, best_rec, best_j, len(parcels & best_rec["parcels"])))
        items.append({"pid": pid, "iso": iso, "nodes": nodes, "rows": rows})

    items.sort(key=lambda it: (it["iso"] or "", it["pid"]), reverse=True)

    lines = [
        "# Stranded cache directories — reference",
        "",
        "Generated by `scripts/stranded_report.py`. Do not edit by hand.",
        "",
        f"`data/project_aliases.json` lists **{len(aliases['unmatched'])}** cached projects whose",
        "`project_id` has no counterpart in the current dataset. For each, this shows what",
        "every gazette actually printed for that unit, **oldest publication first**, so the",
        "point at which a unit left the list is visible rather than inferred.",
        "",
        "**absent** means the 段/小段 has no record at all in that gazette; "
        "**unrelated** means the 段/小段 exists but no record shares at least "
        f"{args.threshold:.0%} of the unit's parcels.",
        "",
        "| gazette | source |",
        "|---|---|",
    ]
    for gid, path in GAZETTES:
        lines.append(f"| {gid} | `{path.name}` |" if path.exists() else f"| {gid} | (missing) |")

    lines += ["", "---", ""]

    for i, it in enumerate(items, 1):
        nodes = it["nodes"]
        first = nodes[0] if nodes else {}
        lines.append(f"## {i}. `{it['pid']}`")
        lines.append("")
        lines.append(f"- 核定日期: `{it['iso'] or '?'}`   members in the 8/11 baseline: **{len(nodes)}**")
        for n in nodes:
            flag = "" if (n.get("land") or "").replace(" ", "").startswith("臺北市") else " **(cell corrupt)**"
            lines.append(f"- baseline node 編號 {n.get('recno')}: `{n.get('land','')}`{flag}")
        lines.append("")
        lines.append("| gazette | 編號 | 核定日期 | 案名 | overlap | parcels shared |")
        lines.append("|---|---|---|---|---|---|")
        for gid, rec, j, shared in it["rows"]:
            if rec is None:
                lines.append(f"| {gid} | — | — | **absent** (no record in this 段/小段) | — | 0 |")
            elif j < args.threshold:
                lines.append(f"| {gid} | {rec['recno']} | {rec['iso']} | *unrelated record in the same 段/小段* | {j:.0%} | {shared} |")
            else:
                name = rec["name"].replace("|", "\\|")
                lines.append(f"| {gid} | {rec['recno']} | {rec['iso']} | {name} | {j:.0%} | {shared} |")
        lines.append("")

    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"written to {args.out}  ({len(items)} items)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())